services:
  redis-db:
    container_name: redis-db
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./dockerDB/redis-data:/data
    command: ["redis-server", "--requirepass", "Abdul1234"]

  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - "27013:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: excalidraw8850
      MONGO_INITDB_ROOT_PASSWORD: Abdul1234
      MONGO_INITDB_DATABASE: excalidraw
    volumes:
      - ./dockerDB/mongo-data:/data/db
